# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/knotifications': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kcmutils': '@latest'
    'frameworks/knotifyconfig': '@latest'
    'frameworks/ktexteditor': '@latest'
    'frameworks/kwallet': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/kiconthemes': '@latest'
    'frameworks/kpeople': '@latest'
    'network/kaccounts-integration': '@same'
