[Desktop Entry]
Name=Telepathy Logger plugin
Name[bs]=Telepathy dnevnički dodatak
Name[ca]=Connector de registre del Telepathy
Name[cs]=Modul záznamů Telepathy
Name[es]=Complemento de gestor de registro de Telepathy
Name[fr]=Module externe de journalisation de Telepathy
Name[ia]=Plugin de Telepathy Logger
Name[it]=Estensione di Telepathy Logger
Name[kk]=Telepathy журналын жүргізу плагині
Name[nl]=Telepathy Logger-plug-in
Name[pt]='Plugin' de Registo do Telepathy
Name[pt_BR]=Plugin do Telepathy Logger
Name[ru]=Модуль ведения журналов Telepathy
Name[sk]=Plugin Telepathy záznam
Name[sr]=Телепатијски прикључак бележника
Name[sr@ijekavian]=Телепатијски прикључак бележника
Name[sr@ijekavianlatin]=Telepathy priključak beležnika
Name[sr@latin]=Telepathy priključak beležnika
Name[sv]=Telepathy-loggningsinsticksprogram
Name[uk]=Додаток ведення журналу Telepathy
Name[x-test]=xxTelepathy Logger pluginxx
Name[zh_CN]=Telepathy 日志插件
Comment=Provides integration with Telepathy Logger
Comment[bs]=Obavlja integraciju s Telepathy dnevnikom
Comment[ca]=Proporciona integració amb l'enregistrador del Telepathy
Comment[cs]=Poskytuje integraci se zaznamenáváním Telepathy
Comment[es]=Proporciona integración con el gestor de registro de Telepathy
Comment[fr]=Fournit une intégration avec la journalisation de Telepathy
Comment[ia]=Il provide integration con Telepathy Logger
Comment[it]=Fornisce integrazione con Telepathy Logger
Comment[kk]=Telepathy журнал жүргізумен біріктіруін қамтамасыз ету
Comment[nl]=Biedt integratie met Telepathy Logger
Comment[pt]=Oferece a integração com o sistema de registo Telepathy Logger
Comment[pt_BR]=Fornece integração com o Telepathy Logger
Comment[ru]=Обеспечивает интеграцию журналов Telepathy
Comment[sk]=Poskytuje integráciu so záznamom Telepathy
Comment[sr]=Пружа интеграцију са телепатијским прикључком бележника
Comment[sr@ijekavian]=Пружа интеграцију са телепатијским прикључком бележника
Comment[sr@ijekavianlatin]=Pruža integraciju sa Telepathy priključkom beležnika
Comment[sr@latin]=Pruža integraciju sa Telepathy priključkom beležnika
Comment[sv]=Tillhandahåller integrering med Telepathy-loggningsinsticksprogram
Comment[uk]=Забезпечує інтеграцію з засобом ведення журналу Telepathy
Comment[x-test]=xxProvides integration with Telepathy Loggerxx
Comment[zh_CN]=提供与 Telepathy 日志的集成

ServiceTypes=KTpLogger/Plugin

X-KDE-Library=ktploggerplugin_tplogger
X-KDE-PluginInfo-Author=Daniel Vrátil
X-KDE-PluginInfo-Email=dvratil@redhat.com
X-KDE-PluginInfo-Name=tplogger
X-KDE-PluginInfo-Version=@KTP_COMMON_INTERNALS_VERSION@
X-KDE-PluginInfo-Website=http://community.kde.org/KTp
X-KDE-PluginInfo-License=GPL
X-KTp-PluginInfo-Version=@KTP_LOGGER_PLUGIN_VERSION@
Encoding=UTF-8
Type=Service
